#!/usr/bin/env python3
"""Generate ../tables/bruteforce_table.tex from step1_bruteforce/results.txt."""
import re, os
HERE = os.path.dirname(os.path.abspath(__file__))
rows = {}
for line in open(os.path.join(HERE, 'step1_bruteforce', 'results.txt')):
    m = re.match(r'LOWN=(\d+) threads=(\d+): SB (\d+) K (\d+): \|D\|=(\d+) distinct=(\d+) \|SEG\|=(\d+) \|FIN\|=(\d+)', line)
    if m:
        lown, th, sb, K, D, dist, seg, fin = map(int, m.groups())
        r = rows.setdefault((sb, K), {'seg': seg, 'fin': fin, 'D': {}})
        r['D'][(lown, th)] = D
    if 'RESULT FAIL' in line and 'NEGATIVE' not in line:
        pass
edges = {13: 15, 17: 21, 19: 28}
with open(os.path.join(HERE, '..', 'tables', 'bruteforce_table.tex'), 'w') as f:
    f.write('% generated by verification/make_tables.py from step1_bruteforce/results.txt\n')
    for (sb, K) in sorted(rows):
        r = rows[(sb, K)]
        d8 = {r['D'][k] for k in r['D'] if k[0] == 8}; d3 = {r['D'][k] for k in r['D'] if k[0] == 3}
        assert len(d8) == 1 and len(d3) == 1, "thread count changed the output"
        f.write('%d & %d & %d & %s & %s & %s & %s \\\\\n' % (sb, edges[sb], K,
                '{:,}'.format(r['seg']).replace(',', '\\,'), '{:,}'.format(d8.pop()).replace(',', '\\,'),
                '{:,}'.format(d3.pop()).replace(',', '\\,'), '{:,}'.format(r['fin']).replace(',', '\\,')))
print(open(os.path.join(HERE, '..', 'tables', 'bruteforce_table.tex')).read())

# ---------------------------------------------------------------- rerun paragraph (Section 8.3)
def grab(path, pat, cast=int):
    for line in open(path):
        m = re.search(pat, line)
        if m: return cast(m.group(1))
    raise SystemExit('pattern %r not found in %s' % (pat, path))
R = os.path.join(HERE, 'rerun')
rl = os.path.join(R, 'rerun_semiprime_reciprocals_4threads.log')
nodes = grab(rl, r'search nodes\s*:\s*(\d+)'); cores = grab(rl, r'cores passing all tests:\s*(\d+)')
shapes = grab(rl, r'completion shapes\s*:\s*(\d+) tried'); alive = grab(rl, r'(\d+) pass parity')
cands = grab(rl, r'\(in \d+ cores\), (\d+) candidate'); unres = grab(rl, r'unresolved cores\s*:\s*(\d+)')
sols = grab(rl, r'solutions found\s*:\s*(\d+)'); secs = grab(rl, r'elapsed:\s*(\d+) s')
assert (nodes, cores, shapes, alive, cands, unres, sols) == (139830520211, 178, 3777, 61, 0, 0, 0)
dl = os.path.join(R, 'dump46.log')
d_cores = grab(dl, r'cores passing Step 1\s*:\s*(\d+)'); d_shapes = grab(dl, r'completion shapes\s*:\s*(\d+) tried')
d_alive = grab(dl, r'(\d+) pass parity'); d_cands = grab(dl, r'\(in \d+ cores\), (\d+) candidate')
d_unres = grab(dl, r'unresolved cores\s*:\s*(\d+)'); d_sols = grab(dl, r'solutions\s*:\s*(\d+)'); d_nodes = grab(dl, r'search nodes\s*:\s*(\d+)')
al = os.path.join(R, 'analyze46_output.txt')
tot = eval(grab(al, r'^totals (\{.*\})', str)); p_sols = grab(al, r'solutions (\d+)'); p_unres = grab(al, r'unresolved_shapes (\d+)')
fmt = lambda n: '{:,}'.format(n).replace(',', '\\,')
with open(os.path.join(HERE, '..', 'tables', 'rerun_text.tex'), 'w') as f:
    f.write('%% generated by verification/make_tables.py from verification/rerun/*.log -- do not edit by hand\n')
    f.write(r"""\paragraph{Re-execution.} For this paper the budget-$46$ program \file{semiprime_reciprocals.cpp} was compiled and executed again with $4$ threads (GCC~13.3.0; a cloud container with $4$ virtual CPUs, Intel Xeon 2.10\,GHz). The output is identical to the recorded \file{proof_run_output.txt}, including the node count $%s$, except for the elapsed time ($%d$\,s, with other jobs running concurrently); log: \file{paper/verification/rerun/}.

\paragraph{Budget-46 cores and a second Step~2.} The engine of \file{semiprime47.cpp}, included unmodified in a small driver, was run with budget $46$; it writes every core kept by Step~1 to a file. It visited $%s$ nodes, kept $%s$ cores, examined $%s$ shapes of which $%s$ survive, found $%s$ candidate stars, $%s$ unresolved cores and $%s$ solutions, in agreement with \cref{tab:results}. The Python Step~2 (\file{analyze47.py}, the logic of \file{complete47.py}) applied to these $%s$ cores with budget $46$ likewise finds $%s$ shapes satisfying \ref{S1}--\ref{S3}, $%s$ satisfying \ref{S1}--\ref{S4} (all with $b=0$), $%s$ candidate stars (also without the bound of $10$ leaves), $%s$ unresolved shapes and $%s$ solutions. This archives the Python check of the budget-$46$ Step~2 mentioned in the repository documentation. Since the Step~1 code of both programs is the same, this is a second \emph{execution} of Step~1, not an independent implementation.
""" % (fmt(nodes), secs, fmt(d_nodes), fmt(d_cores), fmt(d_shapes), fmt(d_alive), fmt(d_cands), fmt(d_unres), fmt(d_sols),
       fmt(tot['cores']), fmt(tot['shapes']), fmt(tot['alive']), fmt(tot['cand_all']), fmt(p_unres), fmt(p_sols)))
    assert tot['alive_nbb1'] == 0 and tot['alive_nbb2plus'] == 0
print(open(os.path.join(HERE, '..', 'tables', 'rerun_text.tex')).read())

# ---------------------------------------------------------------- budget-47 re-execution (if available)
cmp = os.path.join(HERE, 'rerun47', 'rerun47_comparison.txt')
if os.path.exists(cmp):
    c = open(cmp).read()
    ident = 'OVERALL: IDENTICAL (except timing)' in c
    secs = int(re.search(r'search_s\s+\d+\s+(\d+)', c).group(1))
    with open(os.path.join(HERE, '..', 'tables', 'rerun_text.tex'), 'a') as f:
        if ident:
            f.write(r"""
\paragraph{Re-execution of the budget-47 search.} The program \file{semiprime47.cpp} was also executed again, with $4$ threads and the option \code{--dump}, on the same machine. All printed quantities coincide with the recorded \file{run47_output.txt}: the node count $1\,795\,181\,713\,099$, the $22\,382$ cores, the shape and candidate counts, $0$ unresolved cores and $0$ probable primes. The list of $23$ solutions is identical, and the new core dump coincides line by line (as a set of $22\,382$ lines) with \file{cores47.txt.gz}. Only the elapsed time differs ($%s$\,s for the search). Files: \file{paper/verification/rerun47/}.
""" % '{:,}'.format(secs).replace(',', '\\,'))
        else:
            f.write(r"""
\paragraph{Re-execution of the budget-47 search.} The program \file{semiprime47.cpp} was executed again; the comparison with the recorded run found differences, which are reported in \file{paper/verification/rerun47/rerun47_comparison.txt}.
""")
    print('rerun47 paragraph appended; identical =', ident)
