/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (42020 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok113165 : check data t113165 S113165 = true := by decide +kernel

theorem ok357851 : check data t357851 S357851 = true := by decide +kernel

theorem ok244076 : check data t244076 S244076 = true := by decide +kernel

theorem ok106214 : check data t106214 S106214 = true := by decide +kernel

theorem ok467514 : check data t467514 S467514 = true := by decide +kernel

theorem ok135621 : check data t135621 S135621 = true := by decide +kernel

theorem ok53699 : check data t53699 S53699 = true := by decide +kernel

theorem ok410847 : check data t410847 S410847 = true := by decide +kernel

theorem ok308632 : check data t308632 S308632 = true := by decide +kernel

theorem ok191655 : check data t191655 S191655 = true := by decide +kernel

theorem ok630472 : check data t630472 S630472 = true := by decide +kernel

theorem ok214313 : check data t214313 S214313 = true := by decide +kernel

theorem ok537563 : check data t537563 S537563 = true := by decide +kernel

theorem ok15814 : check data t15814 S15814 = true := by decide +kernel

theorem ok612651 : check data t612651 S612651 = true := by decide +kernel

theorem ok441078 : check data t441078 S441078 = true := by decide +kernel

theorem ok451576 : check data t451576 S451576 = true := by decide +kernel

theorem ok376607 : check data t376607 S376607 = true := by decide +kernel

theorem ok201344 : check data t201344 S201344 = true := by decide +kernel

theorem ok462878 : check data t462878 S462878 = true := by decide +kernel

theorem ok36364 : check data t36364 S36364 = true := by decide +kernel

theorem ok173741 : check data t173741 S173741 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
