/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (42008 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok260274 : check data t260274 S260274 = true := by decide +kernel

theorem ok603171 : check data t603171 S603171 = true := by decide +kernel

theorem ok555167 : check data t555167 S555167 = true := by decide +kernel

theorem ok461847 : check data t461847 S461847 = true := by decide +kernel

theorem ok167792 : check data t167792 S167792 = true := by decide +kernel

theorem ok550278 : check data t550278 S550278 = true := by decide +kernel

theorem ok85360 : check data t85360 S85360 = true := by decide +kernel

theorem ok609548 : check data t609548 S609548 = true := by decide +kernel

theorem ok14101 : check data t14101 S14101 = true := by decide +kernel

theorem ok278351 : check data t278351 S278351 = true := by decide +kernel

theorem ok557220 : check data t557220 S557220 = true := by decide +kernel

theorem ok5824 : check data t5824 S5824 = true := by decide +kernel

theorem ok355050 : check data t355050 S355050 = true := by decide +kernel

theorem ok442838 : check data t442838 S442838 = true := by decide +kernel

theorem ok408554 : check data t408554 S408554 = true := by decide +kernel

theorem ok405972 : check data t405972 S405972 = true := by decide +kernel

theorem ok264106 : check data t264106 S264106 = true := by decide +kernel

theorem ok595497 : check data t595497 S595497 = true := by decide +kernel

theorem ok300128 : check data t300128 S300128 = true := by decide +kernel

theorem ok621324 : check data t621324 S621324 = true := by decide +kernel

theorem ok483349 : check data t483349 S483349 = true := by decide +kernel

theorem ok282850 : check data t282850 S282850 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
