/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (41944 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok42420 : check data t42420 S42420 = true := by decide +kernel

theorem ok473855 : check data t473855 S473855 = true := by decide +kernel

theorem ok47086 : check data t47086 S47086 = true := by decide +kernel

theorem ok450124 : check data t450124 S450124 = true := by decide +kernel

theorem ok396860 : check data t396860 S396860 = true := by decide +kernel

theorem ok337337 : check data t337337 S337337 = true := by decide +kernel

theorem ok673550 : check data t673550 S673550 = true := by decide +kernel

theorem ok559475 : check data t559475 S559475 = true := by decide +kernel

theorem ok658998 : check data t658998 S658998 = true := by decide +kernel

theorem ok306435 : check data t306435 S306435 = true := by decide +kernel

theorem ok344516 : check data t344516 S344516 = true := by decide +kernel

theorem ok368626 : check data t368626 S368626 = true := by decide +kernel

theorem ok274893 : check data t274893 S274893 = true := by decide +kernel

theorem ok198377 : check data t198377 S198377 = true := by decide +kernel

theorem ok373683 : check data t373683 S373683 = true := by decide +kernel

theorem ok237821 : check data t237821 S237821 = true := by decide +kernel

theorem ok189488 : check data t189488 S189488 = true := by decide +kernel

theorem ok517796 : check data t517796 S517796 = true := by decide +kernel

theorem ok425399 : check data t425399 S425399 = true := by decide +kernel

theorem ok358840 : check data t358840 S358840 = true := by decide +kernel

theorem ok654612 : check data t654612 S654612 = true := by decide +kernel

theorem ok329508 : check data t329508 S329508 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
