/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (42098 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok651439 : check data t651439 S651439 = true := by decide +kernel

theorem ok332403 : check data t332403 S332403 = true := by decide +kernel

theorem ok533238 : check data t533238 S533238 = true := by decide +kernel

theorem ok626240 : check data t626240 S626240 = true := by decide +kernel

theorem ok573526 : check data t573526 S573526 = true := by decide +kernel

theorem ok2571 : check data t2571 S2571 = true := by decide +kernel

theorem ok91065 : check data t91065 S91065 = true := by decide +kernel

theorem ok413113 : check data t413113 S413113 = true := by decide +kernel

theorem ok315439 : check data t315439 S315439 = true := by decide +kernel

theorem ok165285 : check data t165285 S165285 = true := by decide +kernel

theorem ok318527 : check data t318527 S318527 = true := by decide +kernel

theorem ok143090 : check data t143090 S143090 = true := by decide +kernel

theorem ok312098 : check data t312098 S312098 = true := by decide +kernel

theorem ok437928 : check data t437928 S437928 = true := by decide +kernel

theorem ok617684 : check data t617684 S617684 = true := by decide +kernel

theorem ok208381 : check data t208381 S208381 = true := by decide +kernel

theorem ok11894 : check data t11894 S11894 = true := by decide +kernel

theorem ok360175 : check data t360175 S360175 = true := by decide +kernel

theorem ok221342 : check data t221342 S221342 = true := by decide +kernel

theorem ok236316 : check data t236316 S236316 = true := by decide +kernel

theorem ok238643 : check data t238643 S238643 = true := by decide +kernel

theorem ok571018 : check data t571018 S571018 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
