/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (42012 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok33288 : check data t33288 S33288 = true := by decide +kernel

theorem ok418139 : check data t418139 S418139 = true := by decide +kernel

theorem ok591250 : check data t591250 S591250 = true := by decide +kernel

theorem ok56311 : check data t56311 S56311 = true := by decide +kernel

theorem ok95662 : check data t95662 S95662 = true := by decide +kernel

theorem ok262709 : check data t262709 S262709 = true := by decide +kernel

theorem ok578600 : check data t578600 S578600 = true := by decide +kernel

theorem ok88704 : check data t88704 S88704 = true := by decide +kernel

theorem ok597708 : check data t597708 S597708 = true := by decide +kernel

theorem ok656801 : check data t656801 S656801 = true := by decide +kernel

theorem ok401473 : check data t401473 S401473 = true := by decide +kernel

theorem ok670515 : check data t670515 S670515 = true := by decide +kernel

theorem ok270019 : check data t270019 S270019 = true := by decide +kernel

theorem ok470942 : check data t470942 S470942 = true := by decide +kernel

theorem ok202957 : check data t202957 S202957 = true := by decide +kernel

theorem ok648486 : check data t648486 S648486 = true := by decide +kernel

theorem ok144485 : check data t144485 S144485 = true := by decide +kernel

theorem ok178388 : check data t178388 S178388 = true := by decide +kernel

theorem ok631549 : check data t631549 S631549 = true := by decide +kernel

theorem ok6900 : check data t6900 S6900 = true := by decide +kernel

theorem ok266607 : check data t266607 S266607 = true := by decide +kernel

theorem ok425941 : check data t425941 S425941 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
