/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (42080 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok542929 : check data t542929 S542929 = true := by decide +kernel

theorem ok503164 : check data t503164 S503164 = true := by decide +kernel

theorem ok434441 : check data t434441 S434441 = true := by decide +kernel

theorem ok524144 : check data t524144 S524144 = true := by decide +kernel

theorem ok81314 : check data t81314 S81314 = true := by decide +kernel

theorem ok103595 : check data t103595 S103595 = true := by decide +kernel

theorem ok666300 : check data t666300 S666300 = true := by decide +kernel

theorem ok51382 : check data t51382 S51382 = true := by decide +kernel

theorem ok157634 : check data t157634 S157634 = true := by decide +kernel

theorem ok250569 : check data t250569 S250569 = true := by decide +kernel

theorem ok323431 : check data t323431 S323431 = true := by decide +kernel

theorem ok614602 : check data t614602 S614602 = true := by decide +kernel

theorem ok159405 : check data t159405 S159405 = true := by decide +kernel

theorem ok66802 : check data t66802 S66802 = true := by decide +kernel

theorem ok268216 : check data t268216 S268216 = true := by decide +kernel

theorem ok504714 : check data t504714 S504714 = true := by decide +kernel

theorem ok26802 : check data t26802 S26802 = true := by decide +kernel

theorem ok570346 : check data t570346 S570346 = true := by decide +kernel

theorem ok313204 : check data t313204 S313204 = true := by decide +kernel

theorem ok568997 : check data t568997 S568997 = true := by decide +kernel

theorem ok283683 : check data t283683 S283683 = true := by decide +kernel

theorem ok49149 : check data t49149 S49149 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
