/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (42038 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok147687 : check data t147687 S147687 = true := by decide +kernel

theorem ok526987 : check data t526987 S526987 = true := by decide +kernel

theorem ok131895 : check data t131895 S131895 = true := by decide +kernel

theorem ok115761 : check data t115761 S115761 = true := by decide +kernel

theorem ok129133 : check data t129133 S129133 = true := by decide +kernel

theorem ok379034 : check data t379034 S379034 = true := by decide +kernel

theorem ok583356 : check data t583356 S583356 = true := by decide +kernel

theorem ok447479 : check data t447479 S447479 = true := by decide +kernel

theorem ok75390 : check data t75390 S75390 = true := by decide +kernel

theorem ok642033 : check data t642033 S642033 = true := by decide +kernel

theorem ok30290 : check data t30290 S30290 = true := by decide +kernel

theorem ok108095 : check data t108095 S108095 = true := by decide +kernel

theorem ok68670 : check data t68670 S68670 = true := by decide +kernel

theorem ok507873 : check data t507873 S507873 = true := by decide +kernel

theorem ok604844 : check data t604844 S604844 = true := by decide +kernel

theorem ok206848 : check data t206848 S206848 = true := by decide +kernel

theorem ok552462 : check data t552462 S552462 = true := by decide +kernel

theorem ok294169 : check data t294169 S294169 = true := by decide +kernel

theorem ok101164 : check data t101164 S101164 = true := by decide +kernel

theorem ok380050 : check data t380050 S380050 = true := by decide +kernel

theorem ok91788 : check data t91788 S91788 = true := by decide +kernel

theorem ok550979 : check data t550979 S550979 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
