/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (41994 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok23343 : check data t23343 S23343 = true := by decide +kernel

theorem ok594154 : check data t594154 S594154 = true := by decide +kernel

theorem ok576197 : check data t576197 S576197 = true := by decide +kernel

theorem ok545595 : check data t545595 S545595 = true := by decide +kernel

theorem ok454097 : check data t454097 S454097 = true := by decide +kernel

theorem ok561931 : check data t561931 S561931 = true := by decide +kernel

theorem ok500391 : check data t500391 S500391 = true := by decide +kernel

theorem ok220257 : check data t220257 S220257 = true := by decide +kernel

theorem ok498056 : check data t498056 S498056 = true := by decide +kernel

theorem ok424224 : check data t424224 S424224 = true := by decide +kernel

theorem ok493297 : check data t493297 S493297 = true := by decide +kernel

theorem ok427858 : check data t427858 S427858 = true := by decide +kernel

theorem ok486729 : check data t486729 S486729 = true := by decide +kernel

theorem ok227343 : check data t227343 S227343 = true := by decide +kernel

theorem ok310271 : check data t310271 S310271 = true := by decide +kernel

theorem ok295692 : check data t295692 S295692 = true := by decide +kernel

theorem ok170251 : check data t170251 S170251 = true := by decide +kernel

theorem ok584633 : check data t584633 S584633 = true := by decide +kernel

theorem ok383244 : check data t383244 S383244 = true := by decide +kernel

theorem ok610503 : check data t610503 S610503 = true := by decide +kernel

theorem ok645051 : check data t645051 S645051 = true := by decide +kernel

theorem ok39453 : check data t39453 S39453 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
