/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (41986 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok59277 : check data t59277 S59277 = true := by decide +kernel

theorem ok231338 : check data t231338 S231338 = true := by decide +kernel

theorem ok162159 : check data t162159 S162159 = true := by decide +kernel

theorem ok38956 : check data t38956 S38956 = true := by decide +kernel

theorem ok292925 : check data t292925 S292925 = true := by decide +kernel

theorem ok607269 : check data t607269 S607269 = true := by decide +kernel

theorem ok580959 : check data t580959 S580959 = true := by decide +kernel

theorem ok246337 : check data t246337 S246337 = true := by decide +kernel

theorem ok415318 : check data t415318 S415318 = true := by decide +kernel

theorem ok25433 : check data t25433 S25433 = true := by decide +kernel

theorem ok110170 : check data t110170 S110170 = true := by decide +kernel

theorem ok183112 : check data t183112 S183112 = true := by decide +kernel

theorem ok200207 : check data t200207 S200207 = true := by decide +kernel

theorem ok436172 : check data t436172 S436172 = true := by decide +kernel

theorem ok265735 : check data t265735 S265735 = true := by decide +kernel

theorem ok217955 : check data t217955 S217955 = true := by decide +kernel

theorem ok639866 : check data t639866 S639866 = true := by decide +kernel

theorem ok488022 : check data t488022 S488022 = true := by decide +kernel

theorem ok76578 : check data t76578 S76578 = true := by decide +kernel

theorem ok232283 : check data t232283 S232283 = true := by decide +kernel

theorem ok585580 : check data t585580 S585580 = true := by decide +kernel

theorem ok610991 : check data t610991 S610991 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
