/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (42036 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok404407 : check data t404407 S404407 = true := by decide +kernel

theorem ok371537 : check data t371537 S371537 = true := by decide +kernel

theorem ok422004 : check data t422004 S422004 = true := by decide +kernel

theorem ok399511 : check data t399511 S399511 = true := by decide +kernel

theorem ok188067 : check data t188067 S188067 = true := by decide +kernel

theorem ok495746 : check data t495746 S495746 = true := by decide +kernel

theorem ok512823 : check data t512823 S512823 = true := by decide +kernel

theorem ok285954 : check data t285954 S285954 = true := by decide +kernel

theorem ok18023 : check data t18023 S18023 = true := by decide +kernel

theorem ok644118 : check data t644118 S644118 = true := by decide +kernel

theorem ok61356 : check data t61356 S61356 = true := by decide +kernel

theorem ok290370 : check data t290370 S290370 = true := by decide +kernel

theorem ok429727 : check data t429727 S429727 = true := by decide +kernel

theorem ok177047 : check data t177047 S177047 = true := by decide +kernel

theorem ok439575 : check data t439575 S439575 = true := by decide +kernel

theorem ok365734 : check data t365734 S365734 = true := by decide +kernel

theorem ok616081 : check data t616081 S616081 = true := by decide +kernel

theorem ok271296 : check data t271296 S271296 = true := by decide +kernel

theorem ok419310 : check data t419310 S419310 = true := by decide +kernel

theorem ok168795 : check data t168795 S168795 = true := by decide +kernel

theorem ok518545 : check data t518545 S518545 = true := by decide +kernel

theorem ok383931 : check data t383931 S383931 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
