/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (41920 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok329069 : check data t329069 S329069 = true := by decide +kernel

theorem ok456994 : check data t456994 S456994 = true := by decide +kernel

theorem ok663883 : check data t663883 S663883 = true := by decide +kernel

theorem ok241307 : check data t241307 S241307 = true := by decide +kernel

theorem ok565535 : check data t565535 S565535 = true := by decide +kernel

theorem ok334870 : check data t334870 S334870 = true := by decide +kernel

theorem ok99968 : check data t99968 S99968 = true := by decide +kernel

theorem ok477261 : check data t477261 S477261 = true := by decide +kernel

theorem ok547786 : check data t547786 S547786 = true := by decide +kernel

theorem ok248440 : check data t248440 S248440 = true := by decide +kernel

theorem ok211676 : check data t211676 S211676 = true := by decide +kernel

theorem ok44373 : check data t44373 S44373 = true := by decide +kernel

theorem ok273088 : check data t273088 S273088 = true := by decide +kernel

theorem ok393103 : check data t393103 S393103 = true := by decide +kernel

theorem ok175346 : check data t175346 S175346 = true := by decide +kernel

theorem ok196654 : check data t196654 S196654 = true := by decide +kernel

theorem ok276253 : check data t276253 S276253 = true := by decide +kernel

theorem ok149034 : check data t149034 S149034 = true := by decide +kernel

theorem ok563050 : check data t563050 S563050 = true := by decide +kernel

theorem ok316472 : check data t316472 S316472 = true := by decide +kernel

theorem ok139438 : check data t139438 S139438 = true := by decide +kernel

theorem ok645459 : check data t645459 S645459 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
