/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (41922 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok235243 : check data t235243 S235243 = true := by decide +kernel

theorem ok123213 : check data t123213 S123213 = true := by decide +kernel

theorem ok257285 : check data t257285 S257285 = true := by decide +kernel

theorem ok600333 : check data t600333 S600333 = true := by decide +kernel

theorem ok288495 : check data t288495 S288495 = true := by decide +kernel

theorem ok185545 : check data t185545 S185545 = true := by decide +kernel

theorem ok539932 : check data t539932 S539932 = true := by decide +kernel

theorem ok653703 : check data t653703 S653703 = true := by decide +kernel

theorem ok78775 : check data t78775 S78775 = true := by decide +kernel

theorem ok346609 : check data t346609 S346609 = true := by decide +kernel

theorem ok225614 : check data t225614 S225614 = true := by decide +kernel

theorem ok431663 : check data t431663 S431663 = true := by decide +kernel

theorem ok364247 : check data t364247 S364247 = true := by decide +kernel

theorem ok141183 : check data t141183 S141183 = true := by decide +kernel

theorem ok120344 : check data t120344 S120344 = true := by decide +kernel

theorem ok484904 : check data t484904 S484904 = true := by decide +kernel

theorem ok254570 : check data t254570 S254570 = true := by decide +kernel

theorem ok93135 : check data t93135 S93135 = true := by decide +kernel

theorem ok86465 : check data t86465 S86465 = true := by decide +kernel

theorem ok163194 : check data t163194 S163194 = true := by decide +kernel

theorem ok194673 : check data t194673 S194673 = true := by decide +kernel

theorem ok195081 : check data t195081 S195081 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
