/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 27 subtrees (41903 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok521512 : check data t521512 S521512 = true := by decide +kernel

theorem ok321386 : check data t321386 S321386 = true := by decide +kernel

theorem ok340070 : check data t340070 S340070 = true := by decide +kernel

theorem ok510484 : check data t510484 S510484 = true := by decide +kernel

theorem ok638445 : check data t638445 S638445 = true := by decide +kernel

theorem ok342524 : check data t342524 S342524 = true := by decide +kernel

theorem ok20398 : check data t20398 S20398 = true := by decide +kernel

theorem ok668555 : check data t668555 S668555 = true := by decide +kernel

theorem ok459191 : check data t459191 S459191 = true := by decide +kernel

theorem ok465011 : check data t465011 S465011 = true := by decide +kernel

theorem ok63376 : check data t63376 S63376 = true := by decide +kernel

theorem ok97583 : check data t97583 S97583 = true := by decide +kernel

theorem ok73203 : check data t73203 S73203 = true := by decide +kernel

theorem ok491311 : check data t491311 S491311 = true := by decide +kernel

theorem ok375316 : check data t375316 S375316 = true := by decide +kernel

theorem ok301653 : check data t301653 S301653 = true := by decide +kernel

theorem ok347985 : check data t347985 S347985 = true := by decide +kernel

theorem ok479638 : check data t479638 S479638 = true := by decide +kernel

theorem ok228475 : check data t228475 S228475 = true := by decide +kernel

theorem ok478287 : check data t478287 S478287 = true := by decide +kernel

theorem ok366670 : check data t366670 S366670 = true := by decide +kernel

theorem ok144705 : check data t144705 S144705 = true := by decide +kernel

theorem ok495858 : check data t495858 S495858 = true := by decide +kernel

theorem ok39496 : check data t39496 S39496 = true := by decide +kernel

theorem ok56320 : check data t56320 S56320 = true := by decide +kernel

theorem ok431672 : check data t431672 S431672 = true := by decide +kernel

theorem ok18035 : check data t18035 S18035 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
