/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (42038 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok389524 : check data t389524 S389524 = true := by decide +kernel

theorem ok588487 : check data t588487 S588487 = true := by decide +kernel

theorem ok326140 : check data t326140 S326140 = true := by decide +kernel

theorem ok253200 : check data t253200 S253200 = true := by decide +kernel

theorem ok353259 : check data t353259 S353259 = true := by decide +kernel

theorem ok635923 : check data t635923 S635923 = true := by decide +kernel

theorem ok445215 : check data t445215 S445215 = true := by decide +kernel

theorem ok362426 : check data t362426 S362426 = true := by decide +kernel

theorem ok35481 : check data t35481 S35481 = true := by decide +kernel

theorem ok193740 : check data t193740 S193740 = true := by decide +kernel

theorem ok155449 : check data t155449 S155449 = true := by decide +kernel

theorem ok633490 : check data t633490 S633490 = true := by decide +kernel

theorem ok391336 : check data t391336 S391336 = true := by decide +kernel

theorem ok299029 : check data t299029 S299029 = true := by decide +kernel

theorem ok297259 : check data t297259 S297259 = true := by decide +kernel

theorem ok489588 : check data t489588 S489588 = true := by decide +kernel

theorem ok48503 : check data t48503 S48503 = true := by decide +kernel

theorem ok3878 : check data t3878 S3878 = true := by decide +kernel

theorem ok475020 : check data t475020 S475020 = true := by decide +kernel

theorem ok406983 : check data t406983 S406983 = true := by decide +kernel

theorem ok212440 : check data t212440 S212440 = true := by decide +kernel

theorem ok671191 : check data t671191 S671191 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
