/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (41996 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok118732 : check data t118732 S118732 = true := by decide +kernel

theorem ok482498 : check data t482498 S482498 = true := by decide +kernel

theorem ok350726 : check data t350726 S350726 = true := by decide +kernel

theorem ok304248 : check data t304248 S304248 = true := by decide +kernel

theorem ok620263 : check data t620263 S620263 = true := by decide +kernel

theorem ok9305 : check data t9305 S9305 = true := by decide +kernel

theorem ok205360 : check data t205360 S205360 = true := by decide +kernel

theorem ok623575 : check data t623575 S623575 = true := by decide +kernel

theorem ok516481 : check data t516481 S516481 = true := by decide +kernel

theorem ok661178 : check data t661178 S661178 = true := by decide +kernel

theorem ok382063 : check data t382063 S382063 = true := by decide +kernel

theorem ok530561 : check data t530561 S530561 = true := by decide +kernel

theorem ok180253 : check data t180253 S180253 = true := by decide +kernel

theorem ok469203 : check data t469203 S469203 = true := by decide +kernel

theorem ok528655 : check data t528655 S528655 = true := by decide +kernel

theorem ok646953 : check data t646953 S646953 = true := by decide +kernel

theorem ok28293 : check data t28293 S28293 = true := by decide +kernel

theorem ok209643 : check data t209643 S209643 = true := by decide +kernel

theorem ok394331 : check data t394331 S394331 = true := by decide +kernel

theorem ok513768 : check data t513768 S513768 = true := by decide +kernel

theorem ok181189 : check data t181189 S181189 = true := by decide +kernel

theorem ok372036 : check data t372036 S372036 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
