/- Generated by primitive_egypt.cpp.  Do not edit.  Kernel checks of 22 subtrees (42006 nodes). -/
import SemiprimeEgypt.PrimState412

namespace SemiprimeEgypt.Prim.C412

open SemiprimeEgypt.Prim

theorem ok173204 : check data t173204 S173204 = true := by decide +kernel

theorem ok138517 : check data t138517 S138517 = true := by decide +kernel

theorem ok71347 : check data t71347 S71347 = true := by decide +kernel

theorem ok386600 : check data t386600 S386600 = true := by decide +kernel

theorem ok125692 : check data t125692 S125692 = true := by decide +kernel

theorem ok535708 : check data t535708 S535708 = true := by decide +kernel

theorem ok567940 : check data t567940 S567940 = true := by decide +kernel

theorem ok223553 : check data t223553 S223553 = true := by decide +kernel

theorem ok628450 : check data t628450 S628450 = true := by decide +kernel

theorem ok216432 : check data t216432 S216432 = true := by decide +kernel

theorem ok282291 : check data t282291 S282291 = true := by decide +kernel

theorem ok280262 : check data t280262 S280262 = true := by decide +kernel

theorem ok152376 : check data t152376 S152376 = true := by decide +kernel

theorem ok83027 : check data t83027 S83027 = true := by decide +kernel

theorem ok65031 : check data t65031 S65031 = true := by decide +kernel

theorem ok150539 : check data t150539 S150539 = true := by decide +kernel

theorem ok506189 : check data t506189 S506189 = true := by decide +kernel

theorem ok133154 : check data t133154 S133154 = true := by decide +kernel

theorem ok10492 : check data t10492 S10492 = true := by decide +kernel

theorem ok153370 : check data t153370 S153370 = true := by decide +kernel

theorem ok126583 : check data t126583 S126583 = true := by decide +kernel

theorem ok514286 : check data t514286 S514286 = true := by decide +kernel

end SemiprimeEgypt.Prim.C412
