name = "SemiprimeEgypt"
defaultTargets = ["SemiprimeEgypt"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "3cb72cfd416d1b5ec4b930d67648ef036a5df24f"

[[lean_lib]]
name = "SemiprimeEgypt"
